{{- /* Check for required environment */ -}}
{{- if not (env "MINIKUBE_GATEWAY") -}}
  {{- fail "\n---\nMINIKUBE_GATEWAY env var must be set! Use your `localkube_env` shell function to set it." -}}
{{- end -}}
{{- /* Set global template variables for use in any individual YAML object in this file */ -}}
{{- $appName      := "tpe_prebid_service" -}}
{{- /* trunc 55 instead of 63 to allow for ssh and modules volumes */ -}}
{{- $dnsName          := $appName | replace "_" "-" | trunc 63 -}}
{{- $env              := "development" -}}
{{- $labels           := printf "app: %q\nenv: %q" $appName $env -}}
{{- $registry         := "localhost:5000" -}}
{{- $appImage         := printf "%v/%v/%v:%v" $registry "tapjoy" $appName "baseimage" -}}
{{- $dataDir          := "/data" -}}
{{- $appPort          := 8000 -}}
---
########################################################################################################################
## NETWORK-RELATED MANIFESTS
########################################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: {{ $dnsName | quote }}
  labels: {{ $labels  | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{ $labels | nindent 4 }}
  ports:
  - name: app
    port: 80
    targetPort: {{$appPort}}
---
########################################################################################################################
## STORAGE-RELATED MANIFESTS
########################################################################################################################
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $dnsName | quote }}
  labels: {{ $labels | nindent 4 }}
spec:
  capacity:
    storage: 15Gi # Required setting. Arbitrarily chosen advertised storage capacity.
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    server: {{ env "MINIKUBE_GATEWAY" | quote }}
    path: {{ env "PWD" | quote }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $dnsName | quote }}
  labels: {{ $labels | nindent 4 }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi # Required setting. Matches the advertised capacity of the PersistentVolume.
---
########################################################################################################################
## CONFIGURATION-RELATED MANIFESTS
########################################################################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $dnsName | quote }}
  labels: {{ $labels | nindent 4 }}
data:
  # Placeholder until we need some real ENV for the application
  RACK_ENV: {{ $env | quote }} 

  # new relic values
  PBS_MONITORING_NEWRELIC_APP_NAME: "tpe_prebid_service-dev"
  PBS_MONITORING_NEWRELIC_LICENSE_KEY: {{ default "ThisValueIs40CharacterNewRelicLicenseKey" (env "PBS_MONITORING_NEWRELIC_LICENSE_KEY") | quote }}
  PBS_MONITORING_NEWRELIC_LOG_LEVEL: "error" # // values: https://github.com/sirupsen/logrus/blob/39a5ad12948d094ddd5d5a6a4a4281f453d77562/logrus.go#L25

  # rubicon values
  PBS_ADAPTERS_RUBICON_DISABLED:                "false"
  PBS_ADAPTERS_RUBICON_XAPI_USERNAME:           "username"
  PBS_ADAPTERS_RUBICON_XAPI_PASSWORD:           "password"
  PBS_ADAPTERS_RUBICON_XAPI_ENDPOINT_US_EAST:   "http://exapi-us-east.rubiconproject.com/a/api/exchange.json"
  PBS_ADAPTERS_RUBICON_XAPI_ENDPOINT_US_WEST:   "http://exapi-us-west.rubiconproject.com/a/api/exchange.json"
  PBS_ADAPTERS_RUBICON_XAPI_ENDPOINT_EU:        "http://exapi-eu.rubiconproject.com/a/api/exchange.json"
  PBS_ADAPTERS_RUBICON_XAPI_ENDPOINT_APAC:      "http://exapi-apac.rubiconproject.com/a/api/exchange.json"
  # for mock_service test
  #PBS_ADAPTERS_RUBICON_XAPI_ENDPOINT_US_EAST:   "http://localhost:4646/a/api/exchange.json"
  #PBS_ADAPTERS_RUBICON_XAPI_ENDPOINT_US_WEST:   "http://localhost:4646/a/api/exchange.json"
  #PBS_ADAPTERS_RUBICON_XAPI_ENDPOINT_EU:   "http://localhost:4646/a/api/exchange.json"
  #PBS_ADAPTERS_RUBICON_XAPI_ENDPOINT_APAC:   "http://localhost:4646/a/api/exchange.json"

  # liftoff values
  PBS_ADAPTERS_LIFTOFF_DISABLED: "false"
  PBS_ADAPTERS_LIFTOFF_XAPI_USERNAME: "username"
  PBS_ADAPTERS_LIFTOFF_XAPI_PASSWORD: "password"
  PBS_ADAPTERS_LIFTOFF_XAPI_ENDPOINT_US_EAST: "http://liftoff-us-east.com/givemeads"
  PBS_ADAPTERS_LIFTOFF_XAPI_ENDPOINT_EU: "http://liftoff-eu.com/givemeads"
  PBS_ADAPTERS_LIFTOFF_XAPI_ENDPOINT_APAC: "http://liftoff-apac.com/givemeads"
  # for mock_service test
  #PBS_ADAPTERS_LIFTOFF_XAPI_ENDPOINT_US_EAST: "http://localhost:4646/givemeads"
  #PBS_ADAPTERS_LIFTOFF_XAPI_ENDPOINT_EU: "http://localhost:4646/givemeads"
  #PBS_ADAPTERS_LIFTOFF_XAPI_ENDPOINT_APAC: "http://localhost:4646/givemeads"
---
########################################################################################################################
## WORKLOAD-RELATED MANIFESTS
########################################################################################################################
apiVersion: v1
kind: Pod
metadata:
  name: {{ $dnsName | quote }}
  labels: {{ $labels | nindent 4 }}
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: app
    image: {{ $appImage | quote }}
    imagePullPolicy: Never # We rebuild the baseimage on every `make dev`
    command: ["./deploy/local/entrypoint.sh"]
    # command: ["tail","-f","/dev/null","--"] # Use this as an escape hatch if your app is crashing on turnup
    args: ["prepare_and_run make run"]
    envFrom:
    - configMapRef:
        name: {{ $dnsName | quote }}
    ports:
      - name: app
        containerPort: {{ $appPort }}
        protocol: TCP
    volumeMounts:
      - name: src
        mountPath: {{ list "/go/src" "github.com/tapjoy" $appName | join "/" | quote }}
    readinessProbe:
      httpGet:
        path: /healthz
        port: {{$appPort}}
      initialDelaySeconds: 5
      periodSeconds: 5
  - name: mock-service
    image: localhost:5000/tapjoy/mock_service:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: "PORT"
      value: "4646"
    ports:
    - containerPort: 4646
    livenessProbe:
      tcpSocket:
        port: 4646
  volumes:
  - name: src
    persistentVolumeClaim:
      claimName: {{ $dnsName | quote }}
---
