name: Cross-repo Issue Creation

on:
  pull_request_target:
    types: [closed]
    branches:
      - "master"

jobs:
  cross-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.XREPO_APP_ID }}
          private_key: ${{ secrets.XREPO_PEM }}
      - name: create issue in other repo
        if: "!contains(github.event.pull_request.labels.*.name, 'do not port') && github.event.pull_request.merged"
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          PR_NUMBER: ${{ github.event.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_MERGED_AT: ${{ github.event.pull_request.merged_at }}
        run: |
          BODY="A PR was merged over on PBS-Go

          - https://github.com/prebid/prebid-server/pull/${PR_NUMBER}
          - timestamp: ${PR_MERGED_AT}"
          gh issue create --repo prebid/prebid-server-java \
              --title "Port PR from PBS-Go: ${PR_TITLE}" \
              --body "${BODY}" \
              --label auto
