name: Cross-repo Issue Creation

on:
  pull_request_target:
    types: [closed]
    branches:
      - "master"

jobs:
  cross-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.XREPO_APP_ID }}
          private_key: ${{ secrets.XREPO_PEM }}
      - name: create issue in other repo
        if: "!contains(github.event.pull_request.labels.*.name, 'do not port') && github.event.pull_request.merged"
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          echo -e "A PR was merged over on PBS-Go\n\n- [https://github.com/prebid/prebid-server/pull/${{github.event.number}}](https://github.com/prebid/prebid-server/pull/${{github.event.number}})\n- timestamp: ${{ github.event.pull_request.merged_at}}" > msg
          export msg=$(cat msg)
          gh issue create --repo prebid/prebid-server-java --title "Port PR from PBS-Go: ${{ github.event.pull_request.title }}" \
              --body "$msg" \
              --label auto
