name: Bidder Info Update

on:
  push:
    paths:
      - 'static/bidder-info/**.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if any .yaml file in static/bidder-info/{any-adapter} is updated
        id: check-bidder-info-updated
        run: |
          # Check if any .yaml file in static/bidder-info/{any-adapter} is updated
          if git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -q '^static/bidder-info/.*\.yaml$'; then
            # Get the list of updated YAML files
            updated_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '^static/bidder-info/.*\.yaml$')
          
            # Check if the URL or userMacro in each updated YAML file is updated
            for file in $updated_files; do
              url_changed=$(yq e '.redirect.url' $file | git diff --no-index - $file | grep -q '^\+' && echo true || echo false)
              usermacro_changed=$(yq e '.redirect.userMacro' $file | git diff --no-index - $file | grep -q '^\+' && echo true || echo false)
              if [ "$url_changed" = "true" ] || [ "$usermacro_changed" = "true" ]; then
                echo "::set-output name=url-updated::true"
                break
              fi
            done
          fi
